export enum Regions {
  Cherkasy = 'Cherkasy',
  Chernihiv = 'Chernihiv',
  Chernivtsi = 'Chernivtsi',
  Crimea = 'Crimea',
  Dnipropetrovsk = 'Dnipropetrovsk',
  Donetsk = 'Donetsk',
  IvanoFrankivsk = 'Ivano-Frankivsk',
  Kharkiv = 'Kharkiv',
  Kherson = 'Kherson',
  Khmelnytskyy = 'Khmelnytskyy',
  Kyiv = 'Kyiv',
  Kirovohrad = 'Kirovohrad',
  Luhansk = 'Luhansk',
  Lviv = 'Lviv',
  Mykolayiv = 'Mykolayiv',
  Odessa = 'Odessa',
  Poltava = 'Poltava',
  Rivne = 'Rivne',
  Sumy = 'Sumy',
  Ternopil = 'Ternopil',
  Ukraine = 'Ukraine',
  Vinnytsya = 'Vinnytsya',
  Volyn = 'Volyn',
  Zakarpattia = 'Zakarpattia',
  Zaporizhia = 'Zaporizhia',
  Zhytomyr = 'Zhytomyr',
}
